### ISSUE TITLE
build result run with empty page

### ISSUE THREAD

**Issue by Fauny** [mubaidr/vue-electron-template#1]
mac&win platform, build result run with empty page
run dev every thing ok

**Comment by mubaidr** [comment]
I a working on it. Thanks for reporting.

**Comment by mubaidr** [comment]
I have tested again and results are fine. I have followed following steps: 

```bash
git clone https://github.com/mubaidr/vue-electron-template
cd vue-electron-template
npm install
npm run build
```

Build directory contains an unpacked version and an installer for the same and works fine. 

If it still does not work, please provide OS info and mention if there is any error during build process?

**Comment by Fauny** [comment]
thanks!
I'm using windows 10, and has removed sass*, because I want to use Less and do not have  any .net framework installed

**Comment by Fauny** [comment]
I'v did all steps as following on macos 10.13.4 , node.js v9.8.0:
```
git clone https://github.com/mubaidr/vue-electron-template
cd vue-electron-template
npm install
npm run dev // works fine.
//then, edit package.json, change builds to mac by added  --platform=mac to scripts
npm run build:dir
```
the issue is still there. :(

when I openDevTools, it gave me this message:
```
file://src/main/index.html Failed to load resource: net::ERR_FILE_NOT_FOUND
```

**Comment by mubaidr** [comment]
I have Windows and Linux development environment, cannot test for MacOS. :(

**Comment by mubaidr** [comment]
Fixed: https://github.com/mubaidr/vue-electron-template/commit/50b698361ea29066f21367ee259988be2230d6a3

BTW you don't need to manually set flags for platform or run `pack` and `electron-build` scripts.

Just running:

```bash
npm run build
// or
yarn run build
```
is required. Which will output setup executable in the build directory for current platform. or use `npm run build:dir` script to build application without setup/installer.
