### ISSUE TITLE
Update dependent packages?

### ISSUE THREAD

**Issue by momtboy** [mubaidr/vue-electron-template#1068]
Electron has been updated to version 12.x.x, do you consider updating the corresponding dependency packages?

**Comment by mubaidr** [comment]
I will try to and test updated packages.

**Comment by mubaidr** [comment]
Partial update here, all dependencies updated (including Webpack and Electron): https://github.com/mubaidr/vue-electron-template/commit/92cbf7524b7e7397ca615c271c142394195406fa

`build` works fine, `dev` script is broken, working on it.

**Comment by mubaidr** [comment]
Fixed devtools in: https://github.com/mubaidr/vue-electron-template/commit/ffca7c4ee18ebb728d5a16492cd95c62ad7e923e
