### ISSUE TITLE
How in a production build I could open the dev tool with the vue-devtool installed?

### ISSUE THREAD

**Issue by DannyFeliz** [mubaidr/vue-electron-template#12]
When you run the `npm run build` as is supposed to be it get rid of the devtool and all the development stuff so I have a bug that only happens in the production build so I want to inspect with the development tools. How could I accomplish this?

**Comment by mubaidr** [comment]
Please check this: https://stackoverflow.com/a/45487191

If this does not work or you need more advance tools, let me know. I will
add new build scripts.

**Comment by mubaidr** [comment]
Added in: https://github.com/mubaidr/vue-electron-template/commit/dfdbc76c6e3bece31868b1f3fc05420022d82093

You can have `devtools` open for production build using either:
- ```sh
	set ELECTRON_ENV=development && myapp.exe
	```
- ```sh
	myapp.exe --debug
	```

@DannyFeliz

**Comment by DannyFeliz** [comment]
Thank you man 💪

**Comment by DannyFeliz** [comment]
@mubaidr I'm able to upen de devtool but I want the vue-devtool to.
![image](https://user-images.githubusercontent.com/5460365/41522718-4842b1b2-72a5-11e8-88db-88d9ecf66307.png)
