### ISSUE TITLE
Status of this project?

### ISSUE THREAD

**Issue by dragonDScript** [mubaidr/vue-electron-template#1239]
There hasn't been a single commit since Dec 2021. What's the status of this repository? It also has outdated versions and uses remote

**Comment by mubaidr** [comment]
Vue cli has official(I think) plugin for electronjs.
May be this one: https://github.com/nklayman/vue-cli-plugin-electron-builder

It has better support. But if you think this template suits your need let me know. I will update/fix to latest versions.

**Comment by dragonDScript** [comment]
No, I already used vue cli template, but it's a good idea to update it or archive it to make it clear it's out of support

**Comment by mubaidr** [comment]
https://github.com/mubaidr/vue-electron-template/issues/907
