### ISSUE TITLE
eslint is not working

### ISSUE THREAD

**Issue by nodegin** [mubaidr/vue-electron-template#147]
I cannot get eslint to working when running `npm run dev`, also `npm run lint`does not lint at all, any idea? thanks

**Comment by mubaidr** [comment]
Thanks you for reporting `eslint` is not configured to run during `npm run dev`, I am updating the config to include it. 

While running `npm run lint` will run linter and autofix the found fixable errors.

**Comment by mubaidr** [comment]
Fixed in: https://github.com/mubaidr/vue-electron-template/commit/528c5ab811a057d30cb47b036f65e8ddc2672d10

**Comment by nodegin** [comment]
Nice, thanks!
