### ISSUE TITLE
how to config the webpack to support Dynamic Imports?

### ISSUE THREAD

**Issue by itlixiaolong** [mubaidr/vue-electron-template#205]
I found that there are some js files like 1.js,2.js,3.js...after build,But I can't find where to config this,I config  the webpack to support Dynamic Imports according to the document of official website,but the result is that it create js files like 1.bundle.js ....,Here is my config
![image](https://user-images.githubusercontent.com/26212782/51531486-881cac00-1e78-11e9-9668-229e0c2ba447.png)
Here is the result of build
![image](https://user-images.githubusercontent.com/26212782/51531565-c2864900-1e78-11e9-8258-bb64c5000ac8.png)
What i should do? Thanks for your help!

**Comment by mubaidr** [comment]
Can you please post your webpack config?

**Comment by mubaidr** [comment]
Updated `config` to support chunks and dynamic imports: https://github.com/mubaidr/vue-electron-template/commit/a587bb44d637dffca6efbb3c1e3b553cd1e9d881

**Comment by itlixiaolong** [comment]
Here is my address of my project,you can find my webpack config and the result of build
https://github.com/itlixiaolong/electron-vue-project
