### ISSUE TITLE
App crashes and partially restarts when making changes to electron main script

### ISSUE THREAD

**Issue by alessandrotesoro** [mubaidr/vue-electron-template#232]
Hi there,

First of all thanks for the boilerplate, I've just started experimenting with Electron and found your boilerplate to be really useful. I've found an issue though, when I'm making changes to the main.js file of the electron script, for every change, the "dev" mode that watches for changes to files crashes, the app closes itself and new window is recreated but it's empty because the dev mode has stopped. 

I'm not sure if this is the wanted behavior because I'm new to electron but just wanted to report it. Is this fixable? 

Thank you.

**Comment by mubaidr** [comment]
Hello! It must be a bug, because it is expected to relaunch electron when main script is changed.

I will look into this issue today as soon as possible.

**Comment by mubaidr** [comment]
Fixed in: https://github.com/mubaidr/vue-electron-template/commit/d300ab950a7b1441d22a4ee64471b27197dae59c
