### ISSUE TITLE
Resolve alias is not working

### ISSUE THREAD

**Issue by yrq110** [mubaidr/vue-electron-template#412]
In [`_scripts/webpack.renderer.config.js`](https://github.com/mubaidr/vue-electron-template/blob/master/_scripts/webpack.renderer.config.js#L119).

```js
...
 '@': path.join(__dirname, './src/'),
...
```

should be

```js
...
 '@': path.join(__dirname, '../src/renderer'),
...
```

and for example the code below will working

```js
import SystemInformation from '@/components/About/SystemInformation.vue'
...
```

Same problem with [src](https://github.com/mubaidr/vue-electron-template/blob/master/_scripts/webpack.renderer.config.js#L120) alias and config in [`_scripts/webpack.main.config.js`](https://github.com/mubaidr/vue-electron-template/blob/master/_scripts/webpack.main.config.js#L52)

**Comment by yrq110** [comment]
Ok I got it.

It's not working, the error info is:
```
./src/renderer/components/Help.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/components/Help.vue?vue&type=script&lang=js&)
Module not found: Error: Can't resolve '@/renderer/components/About/SystemInformation.vue' in '/Users/yrq/Desktop/project/vue-electron/src/renderer/components'
```

If change `@` value to `path.join(__dirname, '../src/')`, it works.

**Comment by mubaidr** [comment]
Thanks, I have updated the resolve path. 

https://github.com/mubaidr/vue-electron-template/commit/65aebf9bfb02efea39900ce3750f4d98394e3c95
