### ISSUE TITLE
how can I see changes when I save my edits

### ISSUE THREAD

**Issue by oussama-he** [mubaidr/vue-electron-template#424]
I would like to see changes after I save my edits.
How can I do this, now to see changes I stop the `npm run dev` in terminal then I restart it.
But what I want is to see changes after save like in normal vue project.

Any help, please.
Thank you in advance.

**Comment by mubaidr** [comment]
That is how it is supposed to work, it should auto update thebapp whenever some file in project changes. Is there any error in the console?

**Comment by oussama-he** [comment]
Sorry for the inconvenience, it works now, I don't know how, but it works.
I tried before posting the question but didn't work for me, but now it works.

Anyway thank you.
