### ISSUE TITLE
Customizing app Icon from default

### ISSUE THREAD

**Issue by Muchwat** [mubaidr/vue-electron-template#481]
Where do i change the app icon url, so as to change it from default electron icon to mine

**Comment by Muchwat** [comment]
I have solved it by placing icon.png in the build folder, icon.ico also works fine. For more information check [](https://www.electron.build/icons)

**Comment by mubaidr** [comment]
Or you can also change icon by changing the icon path here: https://github.com/mubaidr/vue-electron-template/blob/master/_scripts/build.js#L48
