### ISSUE TITLE
Question about workers

### ISSUE THREAD

**Issue by marctwen** [mubaidr/vue-electron-template#484]
Please show an example of how to execute worker. And please tell me if it can communicate with the renderrer process?

**Comment by mubaidr** [comment]
Regarding the workers you can use either nodejs workers or child_process module. Both are very similar.  You should use some thread/worker management library like https://github.com/watson/worker-threads-pool to easily manage communication with child process/workers. 
Also look at this: 
https://www.html5rocks.com/en/tutorials/workers/basics/
https://www.freecodecamp.org/news/node-js-child-processes-everything-you-need-to-know-e69498fe970a/

For main/renderer process communication, this is used for menu/view changes: 
from main: https://github.com/mubaidr/vue-electron-template/blob/master/src/main/index.js#L135
from renderer: https://github.com/mubaidr/vue-electron-template/blob/master/src/renderer/main.js#L27
