### ISSUE TITLE
Include Express.js

### ISSUE THREAD

**Issue by fabiiomiiguel** [mubaidr/vue-electron-template#500]
Are interested in a pull request to include express js in your template?

**Comment by mubaidr** [comment]
Can you please explain?

**Comment by fabiiomiiguel** [comment]
Before something congratz for your amazing job at this template. So... I figured out how to integrate, with your template, the express js plus sequelize to use a local database. If your are interested, I can pull request that :)

**Comment by mubaidr** [comment]
That would be great, but I think a separate branch would be more appropriate for this template. I will include this template information in the main read-me for the users. :)

Thanks
