### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by jbeguna04** [mubaidr/vue-electron-template#55]
Hello @mubaidr , Would you like to have any icon/logo for this project?

**Comment by jbeguna04** [comment]
Let me propose some designs as soon as I finished them. Thanks!

**Comment by jbeguna04** [comment]
Hello @mubaidr , I have created a logo for the project
![image](https://user-images.githubusercontent.com/35353768/44251057-9e6b6f80-a229-11e8-998a-0e5a98bfb2c3.png)
I would like to ask your opinion about it. And please tell me the final name of the project
Thank you

**Comment by jbeguna04** [comment]
![image](https://user-images.githubusercontent.com/35353768/44251135-dc689380-a229-11e8-9213-c487ca045c84.png)

**Comment by jbeguna04** [comment]
![image](https://user-images.githubusercontent.com/35353768/44255560-12614400-a239-11e8-9208-ca5e6e140314.png)
Here is it. What do you think?

**Comment by mubaidr** [comment]
I think the first one looks petty good. What do you say?

**Comment by jbeguna04** [comment]
Yes it is. Hope you like it. Btw, Do you have any final name for your project. So that i could put a title after the logo for any logo types
Thanks in advance :)

**Comment by jbeguna04** [comment]
Yes it is. Hope you like it. Btw, Do you have any final name for your project. So that i could put a title after the logo for any logo types
Thanks in advance :)

**Comment by mubaidr** [comment]
Name is same as the title of this repo, as this is repository for template.

**Comment by jbeguna04** [comment]
![image](https://user-images.githubusercontent.com/35353768/44296282-45194400-a2ee-11e8-9ab2-e43019081329.png)
 You can choose color here.

**Comment by mubaidr** [comment]
5th color or light blue color is very nice. 

Please create pull request to include banner, logo and credits. 👍

**Comment by jbeguna04** [comment]
Sure . Thank you for your cooperation

**Comment by jbeguna04** [comment]
![image](https://user-images.githubusercontent.com/35353768/44296681-e6f05f00-a2f5-11e8-8ed7-f07fdec68135.png)
This is a logotype for the project

**Comment by mubaidr** [comment]
Lovely! Thanks for your hard work! 👍

**Comment by jbeguna04** [comment]
Creating a Pull Request now. Thank you again

**Comment by jbeguna04** [comment]
Where are we using the logo for this plugin mainly? I visited Vue.js website and searched any plugins but i couldn't find them. Thanks in advance

**Comment by mubaidr** [comment]
Currently we only plan to use banner in the readme. Later, I will add icon where required.

**Comment by mubaidr** [comment]
@all-contributors please add @jbeguna04 for design
