### ISSUE TITLE
Works well in dev mode, build successfully but can't launch after building.

### ISSUE THREAD

**Issue by JIACHENG135** [mubaidr/vue-electron-template#632]
Hello mubaidr,

Thank you so much for your brilliant work. I'm a beginner in electron. These template is convenient. During the dev and build stage, app works well. However, after building, it can't launch in Windows 10 64bit. Here is my project repo:[https://github.com/JIACHENG135/Electron-Vue-Book-Searcher.git](url). You can represent this situation by `npm install` and `npm run build`. Did I miss anything? Thank you so much for your time again.

**Comment by mubaidr** [comment]
The default setup works fine. This looks like something in your setup. I will fork and check it. In the meantime please note that you can debug the built app by passing `--debug` parameter to the exe/shortcut. :)

**Comment by mubaidr** [comment]
Looks like there is a need to update static path folders. Working on it.

**Comment by mubaidr** [comment]
Fixed here: https://github.com/JIACHENG135/Electron-Vue-Book-Searcher/pull/1

You should load statis resource by `static/` path not `/static/`.

**Comment by mubaidr** [comment]
Also created a pull request with bug fix on your repository: https://github.com/JIACHENG135/Electron-Vue-Book-Searcher/pull/1

**Comment by JIACHENG135** [comment]
Hello Muhanmmad,

Thank you so much for debugging for me. I really appreciate it. Sorry for
replying late I just finished my course project. Anyway hope you safe and
health!

Sincerely,
Jiacheng
