### ISSUE TITLE
console.log() not printing

### ISSUE THREAD

**Issue by Fusseldieb** [mubaidr/vue-electron-template#640]
The Electron App starts up just nicely, but any `console.log()` that I use inside `src/main/index.js` doesn't show up inside the console, no matter where I put it in the file.

Any help is greatly appreciated!

**Comment by mubaidr** [comment]
To enable it un-comment the following line:
https://github.com/mubaidr/vue-electron-template/blob/master/_scripts/dev-runner.js#L48

**Comment by Fusseldieb** [comment]
Thanks for the incredibly fast response!

I tried both, but with both I don't get any output whatsoever. 

![image](https://user-images.githubusercontent.com/4715129/77850667-759fb000-71aa-11ea-9c92-8f92ea0bb6f7.png)

The first method opens two completely empty terminal windows and the remote debugger in VSCode doens't show anything from my `console.log` also, no matter on which process I attach it (electron, node, ...)

![image](https://user-images.githubusercontent.com/4715129/77850697-9b2cb980-71aa-11ea-9169-a58d0ddb6ff0.png)

Thanks in advance!

**Comment by mubaidr** [comment]
Ok I will look into this matter.

**Comment by mubaidr** [comment]
There is bug in the console logging code, I am fixing it.

**Comment by mubaidr** [comment]
should be fixed in: https://github.com/mubaidr/vue-electron-template/commit/f783f6932bd54f6b32392307437793f096cea697

**Comment by Fusseldieb** [comment]
Wow! Thanks for the incredibly fast fix!

![image](https://user-images.githubusercontent.com/4715129/77945196-a5c47d00-7296-11ea-8296-31f3fce9cc96.png)

Works perfectly now! 🥇
