### ISSUE TITLE
trojan in node_modules...

### ISSUE THREAD

**Issue by Helixar** [mubaidr/vue-electron-template#641]
I don't really think that's normal, you know? 
![image](https://user-images.githubusercontent.com/39304785/78363945-f13f9980-75bc-11ea-86f6-ed395d48557a.png)

**Comment by mubaidr** [comment]
Could be a false positive. Also `app-builder` is used by this package `electron-builder`, so please visit the https://github.com/electron-userland/electron-builder to report clarify this.
