### ISSUE TITLE
Disable or customize Context menu 

### ISSUE THREAD

**Issue by jdounivers** [mubaidr/vue-electron-template#682]
Hello,

I'm trying to disable or change the context menu but everything i saw on tutoriel doesn't seems to work.
Is there a specific way to change it with this template ?

**Comment by mubaidr** [comment]
You mean context menu or application menu? Also which tutorial please?

**Comment by jdounivers** [comment]
I mean the context menu, this :
![image](https://user-images.githubusercontent.com/61185813/81294726-92fc4f80-906f-11ea-841d-ac0362d2ea6c.png)
And i tried different tutorial.
Doing this (as i saw in [off doc](https://www.electronjs.org/docs/api/menu#render-process)) :
`
window.addEventListener('contextmenu', (e) => {
  e.preventDefault()
  menu.popup({ window: remote.getCurrentWindow() })
}, false)
`

or this using electron-context-menu dependency

**Comment by mubaidr** [comment]
This should work as expected. Can you share your code?

**Comment by jdounivers** [comment]
I didn't change a lot of things.
Here is my src/renderer/main.js :
```js
import Vue from 'vue'
import App from './App.vue'
import './assets/style/main.scss'
import router from './router/index'
import store from './store/index'

const { remote } = require('electron')
const { Menu, MenuItem } = remote

const isDev = process.env.NODE_ENV === 'development'

Vue.config.devtools = isDev
Vue.config.performance = isDev
Vue.config.productionTip = isDev

// tslint:disable-next-line: no-unused-expression
new Vue({
  el: '#app',
  router,
  store,
  render: h => h(App),
})

const menu = new Menu()
menu.append(new MenuItem({ type: 'separator' }))

window.addEventListener('contextmenu', (e) => {
  e.preventDefault()
  menu.popup({ window: remote.getCurrentWindow() })
}, false)

// to avoild accesing electorn api from web app build
if (window && window.process && window.process.type === 'renderer') {
  const { ipcRenderer } = require('electron')

  // handle menu event updates from main script
  ipcRenderer.on('change-view', (event, data) => {
    if (data.route) {
      router.push(data.route)
    }
  })
}
```

**Comment by mubaidr** [comment]
Looks good to me, I will check and update you.

**Comment by jdounivers** [comment]
Thanks
and thanks for your quick answer

**Comment by mubaidr** [comment]
It works as expected for me. 

![Untitled](https://user-images.githubusercontent.com/2222702/81298220-e8475980-908d-11ea-908c-8e680332b96e.png)


Code sample used: 
```js
const { remote } = require('electron')
const { Menu, MenuItem } = remote
const menu = new Menu()
menu.append(new MenuItem({ label: 'Home' }))
menu.append(new MenuItem({ type: 'separator' }))
menu.append(new MenuItem({ label: 'Other' }))

window.addEventListener(
  'contextmenu',
  (e) => {
    e.preventDefault()
    menu.popup({ window: remote.getCurrentWindow() })
  },
  false
)

```

**Comment by jdounivers** [comment]
I saw where is the difference :

```
  mainWindow = new BrowserWindow({
    backgroundColor: '#fff',
    width: 960,
    height: 540,
    minWidth: 960,
    minHeight: 540,
    // useContentSize: true,
    webPreferences: {
      nodeIntegration: true,
      nodeIntegrationInWorker: false,
      webSecurity: false,
    },
    frame: false,
    show: false,
    resizable: false
  })
```

**Comment by jdounivers** [comment]
With `frame : false` the contextmenu doesn't work anymore

**Comment by mubaidr** [comment]
Then it must be electronjs implementation,nothing to do with this template.
