### ISSUE TITLE
Modify src/main causes multiple electron on reload

### ISSUE THREAD

**Issue by loongmxbt** [mubaidr/vue-electron-template#707]
OS: MacOS 10.15.3
Step1: yarn run dev
Step2: modify `src/main/index.js`, e.g. add a new line
Step3: automatically reload and a new electron appears, the old one become blank screen.
Step4. I can cmd+q quit the new electron window, but the blank window can't quit easily. I need to open task manager to close it.

BTW: no such problems while modifying renderer files.
![image](https://user-images.githubusercontent.com/5986600/83711546-18b2f100-a656-11ea-848e-eab09c70f749.png)

**Comment by mubaidr** [comment]
I don't own a MAC but I will try to reproduce this behavior on Windows.

**Comment by mubaidr** [comment]
It does not happen on Windows. Can you please share more info?

- Electron version
- Your run command
- Any flags?

**Comment by ksh2016** [comment]
@mubaidr It happened on my MacBook too

**Comment by mubaidr** [comment]
@ksh2016 Any error message? or any log in the console?

**Comment by ksh2016** [comment]
@mubaidr I don't think anything useful in the console, and will find some detail info ,maybe later these days

**Comment by mubaidr** [comment]
I really have no option for debugging right now as I said I do not own a Mac OS device. I would appreciate if you could contribute.

**Comment by mubaidr** [comment]
Cannot reproduce this issue on my system. I will re-open this issue once we have any confirmation.
