### ISSUE TITLE
An unhandled error occurred inside electron-build

### ISSUE THREAD

**Issue by ksh2016** [mubaidr/vue-electron-template#720]
Hi, I add a dll file to the project, then I tried to run `yarn run dev`,An error occurred as below.
![image](https://user-images.githubusercontent.com/20473833/84969869-21beba80-b14c-11ea-8417-36a176ae32af.png)
When I do the same thing in a blank project with electron, electron-builder and the dll file, it works just fine.

Environments:
- Windows 10
- Python 2.7.18
- ffi-napi 3.0.1
- electron-builder 22.1.0

**Comment by mubaidr** [comment]
This is related to your build environment. Native modules are required to be re-compiled according to your OS & Electron js version, that is where this is failing. For more info: https://www.electronjs.org/docs/tutorial/using-native-node-modules
