### ISSUE TITLE
Update to the latest version , the MAC can't build

### ISSUE THREAD

**Issue by Gaitin** [mubaidr/vue-electron-template#78]
Update to the latest version , the MAC can't build

**Comment by mubaidr** [comment]
Previus version worked fine? 


I will take a look. In the meantime please make sure you are not using dev branch.

**Comment by Gaitin** [comment]
Electron is already available in the local area. When pack it, it will download  electron again.sometimes download error. so i failed .how can i do not download it when pack it.

**Comment by mubaidr** [comment]
Electron uses different versions for development and build. But if you have already built the application once using an older version, please replace the same version in `package.json`. i.e.

replace this: 
```json
"electron": "^2.0.6",
```
with:
```json
"electron": "2.0.4",
```

**Comment by mubaidr** [comment]
I am closing this issue, If you think this is still not solved please feel free to re-open this issue.
