### ISSUE TITLE
Error when npm install

### ISSUE THREAD

**Issue by hjiul** [mubaidr/vue-electron-template#787]
Hello,
I am very new to programming in general.
I start to understand the all npm system but it seems that i still have to understand more..

Here is my log, can someone explain me what i did wrong ? 
(i run the shell as admin)

PS D:\apps\qusar\test3> git clone https://github.com/mubaidr/vue-electron
Cloning into 'vue-electron'...
remote: Enumerating objects: 48, done.
remote: Counting objects: 100% (48/48), done.
remote: Compressing objects: 100% (48/48), done.
remote: Total 4902 (delta 40), reused 0 (delta 0), pack-reused 4854
Receiving objects: 100% (4902/4902), 8.54 MiB | 267.00 KiB/s, done.

Resolving deltas: 100% (3461/3461), done.
PS D:\apps\qusar\test3> cd vue-electron
PS D:\apps\qusar\test3\vue-electron> npm install
npm WARN tarball tarball data for material-design-icons@3.0.1 (sha1-mnHEh0chjrylHlGmbaaCA4zct78=) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for app-builder-bin@3.5.9 (sha512-NSjtqZ3x2kYiDp3Qezsgukx/AUzKPr3Xgf9by4cYt05ILWGAptepeeu0Uv+7MO+41o6ujhLixTou8979JGg2Kg==) seems to be corrupted. Trying one more time.
npm ERR! code EPERM
npm ERR! syscall unlink
npm ERR! path D:\apps\qusar\test3\vue-electron\node_modules\.staging\material-design-icons-61adc0d8\device\2x_web\ic_signal_wifi_2_bar_white_36dp.png
npm ERR! errno -4048
npm ERR! Error: EPERM: operation not permitted, unlink 'D:\apps\qusar\test3\vue-electron\node_modules\.staging\material-design-icons-61adc0d8\device\2x_web\ic_signal_wifi_2_bar_white_36dp.png'
npm ERR!  [OperationalError: EPERM: operation not permitted, unlink 'D:\apps\qusar\test3\vue-electron\node_modules\.staging\material-design-icons-61adc0d8\device\2x_web\ic_signal_wifi_2_bar_white_36dp.png'] {
npm ERR!   cause: [Error: EPERM: operation not permitted, unlink 'D:\apps\qusar\test3\vue-electron\node_modules\.staging\material-design-icons-61adc0d8\device\2x_web\ic_signal_wifi_2_bar_white_36dp.png'] {
npm ERR!     errno: -4048,
npm ERR!     code: 'EPERM',
npm ERR!     syscall: 'unlink',
npm ERR!     path: 'D:\\apps\\qusar\\test3\\vue-electron\\node_modules\\.staging\\material-design-icons-61adc0d8\\device\\2x_web\\ic_signal_wifi_2_bar_white_36dp.png'
npm ERR!   },
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path: 'D:\\apps\\qusar\\test3\\vue-electron\\node_modules\\.staging\\material-design-icons-61adc0d8\\device\\2x_web\\ic_signal_wifi_2_bar_white_36dp.png',
npm ERR!   parent: 'vue-electron'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\esteban\AppData\Roaming\npm-cache\_logs\2020-08-23T03_05_10_342Z-debug.log
PS D:\apps\qusar\test3\vue-electron>

Thanks :)

**Comment by mubaidr** [comment]
```bash
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
```

This files are probably in use by some other process. Just try to install deps again, it should work fine.
