### ISSUE TITLE
Prefetching/Preloading modules

### ISSUE THREAD

**Issue by ram-you** [mubaidr/vue-electron-template#79]
Hi, can you please implement Prefetching/Preloading modules to have something like this in the header tag : 
`<link rel="prefetch" href="login-modal-chunk.js">`
?

Thank you.

**Comment by mubaidr** [comment]
This should be working by default. But I will review and post here the results.

**Comment by mubaidr** [comment]
Confirmed. There are two use cases; 

- If the asset you want to prefetch is an static asset, place it in `static` directory and link it in `index.html`

- If asset is dynamic (means requires compilation sass, js etc) then:
update your import: 
```js
import("LoginModal")
```
to: 
```js
import(/* webpackPrefetch: true */ "LoginModal")
```
This will prefetch the asset. 

- Another more customizable option is to use this web-pack plugin:
https://github.com/numical/script-ext-html-webpack-plugin

**Comment by mubaidr** [comment]
Great! 👍
