### ISSUE TITLE
main process hot reload cause duplicated windows

### ISSUE THREAD

**Issue by julien-Lachaux** [mubaidr/vue-electron-template#797]
hello,
i notice an error in your script dev-runner.js, when you kill the process using his pid you miss to send a 'SIGKILL' instead of the default 'SIGTERM'. using SIGTERM cause windows duplication when you hot reload a modification in a file of the main process. to fix it just modify the line 29

```javascript
before:
kill(pid, (err) => {

after:
kill(pid, 'SIGKILL', (err) => {
```

hope this will help you.

btw thanks a lot for this boilerplate he work very well :)

**Comment by mubaidr** [comment]
Nice find, `SIGKILL` definitely sounds good for this purpose. 

updated in: https://github.com/mubaidr/vue-electron-template/commit/148573d74bcb8a3e4cba1fed3bf493690a335cf0

Thanks 👍
