### ISSUE TITLE
Vue 3 support?

### ISSUE THREAD

**Issue by VictorioBerra** [mubaidr/vue-electron-template#907]
Any idea when/if we will see Vue 3 support now that Vue 3 is officially out?

**Comment by mubaidr** [comment]
I recommend using `vue/cli` to setup new project. You can add `https://github.com/nklayman/vue-cli-plugin-electron-builder` plugin to enable electron build/scripts support. 

```bash
npm install -g @vue/cli
vue create hello-world
vue add electron-builder
```

If there are specific reason you prefer this version, let me know. I will try to introduce vue 3 support.
